/**
 * Extract Options interface fields from highcharts.d.ts.
 *
 * Outputs:
 *   src/generated/options-fields.json — Options interface field metadata
 *
 * Module mapping and chart types are generated by generate-module-map.mjs
 * using Highcharts' actual runtime registry (more accurate than source parsing).
 *
 * Run: npx tsx scripts/generate-schema.ts
 */
import ts from "typescript";
import fs from "node:fs";
import path from "node:path";

const HIGHCHARTS_DTS = path.resolve("node_modules/highcharts/highcharts.d.ts");
const GENERATED_DIR = path.resolve("src/generated");

fs.mkdirSync(GENERATED_DIR, { recursive: true });

// ─── Extract Options interface fields from highcharts.d.ts ───────────────────

const program = ts.createProgram([HIGHCHARTS_DTS], {
  target: ts.ScriptTarget.ESNext,
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
});
const checker = program.getTypeChecker();
const sourceFile = program.getSourceFile(HIGHCHARTS_DTS)!;

interface OptionsField {
  name: string;
  type: string;
  description: string;
  optional: boolean;
  isArray: boolean;
}

const optionsFields: OptionsField[] = [];
ts.forEachChild(sourceFile, (node) => {
  if (!ts.isInterfaceDeclaration(node) || node.name.text !== "Options") return;
  for (const member of node.members) {
    if (!ts.isPropertySignature(member) || !member.name) continue;
    const name = (member.name as ts.Identifier).text;
    const symbol = checker.getSymbolAtLocation(member.name);
    const description = symbol
      ? ts.displayPartsToString(symbol.getDocumentationComment(checker)).replace(/\n/g, " ").replace(/^\(.*?\)\s*/, "").trim()
      : name;
    const optional = !!member.questionToken;

    let typeName = "";
    let isArray = false;
    if (member.type) {
      const typeText = member.type.getText(sourceFile);
      isArray = typeText.includes("Array<");
      typeName = typeText
        .replace(/Array<([^>]+)>/g, "$1")
        .replace(/[()]/g, "")
        .split("|")[0]
        .trim();
    }

    optionsFields.push({ name, type: typeName, description, optional, isArray });
  }
});

fs.writeFileSync(
  path.join(GENERATED_DIR, "options-fields.json"),
  JSON.stringify(optionsFields, null, 2) + "\n"
);

console.log(`✅ options-fields.json (${optionsFields.length} fields)`);
